In [5]:
import numpy as np

In [ ]:
mylist = [1,2,3]
type(mylist)

list

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [1]:
matrix  =  [[1,2,3],[4,5,6],[7,8,9]]

In [2]:
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
 np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [16]:
len( np.linspace(0,10,4))

4

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(1)

array([0.99312665])

In [21]:
np.random.rand(5,2)

array([[0.21072404, 0.39911292],
       [0.10760801, 0.09415683],
       [0.93061011, 0.99325622],
       [0.61383901, 0.99056003],
       [0.89069395, 0.02413514]])

In [25]:
np.random.randn(10)

array([ 0.43969591,  2.38367075,  0.89793374, -0.23109327,  0.43177257,
        1.08638501, -1.14725111,  0.51335461,  0.11872827, -0.69862622])

In [27]:
np.random.randint(0,101,20)

array([87, 68,  4, 84, 98, 81, 76, 78, 58, 81, 21, 81, 74, 98, 72, 82, 27,
       74, 44, 97])

In [29]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [30]:
arr  = np.arange(0,25)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranArr  = np.random.randint(0,101,10)
ranArr

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])