In [1]:
import numpy as np

In [2]:
arr  =  np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

np.int64(8)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[3:9]

array([3, 4, 5, 6, 7, 8])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_arr =  arr[0:5]

In [16]:
slice_arr

array([100, 100, 100, 100, 100])

In [17]:
slice_arr[:]  = 99

In [18]:
slice_arr

array([99, 99, 99, 99, 99])

In [21]:
arr2d  =  np.array( [[5,10,15],[20,25,30],[35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr2d.shape


(3, 3)

In [24]:
arr2d[2]

array([35, 40, 45])

In [25]:
arr2d[2,1]

np.int64(40)

In [26]:
arr2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [27]:
arr2d[2:]

array([[35, 40, 45]])

In [28]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [30]:
bool_arr  = arr>4

In [31]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [32]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])