In [1]:
import numpy as np

In [4]:
arr = np.arange(0,10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Operations

In [7]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [9]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
arr/arr  #returns not a value since cannot div by 0

/tmp/ipython-input-12-3842557924.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr  #returns not a value since cannot div by 0


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [13]:
 np.sqrt(arr)


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
np.log(arr)

/tmp/ipython-input-14-3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [15]:
 np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [16]:
arr.sum()

np.int64(45)

In [17]:
arr.mean()

np.float64(4.5)

In [18]:
arr.max()

np.int64(9)

In [20]:
arr.std()

np.float64(2.8722813232690143)